### ISSUE TITLE
Schematic's Not Placing (SchematicShop)

### ISSUE THREAD

**Issue by NortherDogAJ** [drtshock/SchematicShop#12]
I have bought your plugin (ShematicShop) And I have set up the config and everything, Everything was set up correctly I believe, I made a schematic named "Sugarcane_Farm" And I restarted my server, Then did (/ss) It worked, It all showed up correctly with the name "Sugarcane Farm" Lore showed up correctly too. Then on the server console I added my self to the schematic, It said I was added to the schematic. Then I clicked the Sugarcane Farm and it popped up in my inventory, And I placed it in my world on Minecraft. I waited a good 10 minutes, Nothing showed up in the world. But I think 1 error showed up in the console the PasteBin URL is : http://pastebin.com/75T2buNZ )) And my YML Config can be found at : http://pastebin.com/8M4GiKRx )) Problem: Schematics won't paste in the world.

**Comment by NortherDogAJ** [comment]
I think that was an issue with my PerWorldPlugin I removed that, restarted my server and tried again, And then I got this error  http://pastebin.com/3wMp720B

**Comment by NortherDogAJ** [comment]
Oh, And when I place the block it just comes back to my inventory.

**Comment by Empasm** [comment]
one month and no answer? yeah im assuming the dev abandoned this project?

**Comment by drtshock** [comment]
No @Karrade. And this NPE was most likely due to misconfiguration as this plugin isn't very friendly if the config is off.

**Comment by Empasm** [comment]
http://pastebin.com/HKRES30G

stupid github formatting lol

**Comment by drtshock** [comment]
You need to put the schematics in the schematicshop schematic folder, not the worldedit folder.

**Comment by Empasm** [comment]
ok well thank you, maybe the plugin should be changed to save the schematics in the corrent folder then.

**Comment by Empasm** [comment]
look at that, stopped server moved schematic to correct folder and hey ya know what, it still doesnt work.... or you know some kind of documentation?

18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at java.lang.Thread.run(Thread.java:745)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:740)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.PlayerInteractManager.interact(PlayerInteractManager.java:503)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at net.minecraft.server.v1_8_R2.ItemStack.placeItem(ItemStack.java:157)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:126)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at java.lang.reflect.Method.invoke(Method.java:483)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]:   at com.puzlinc.schematicshop.Events.onBlockPlace(Events.java:138)
18.05 13:54:58 [Server] INFO [13:54:58 WARN]: java.lang.NullPointerException

**Comment by drtshock** [comment]
Your stack trace is incomplete and not in a gist. Please fix that and include what you did to produce it, which version of the plugin you're using, and your startup log.

As far as the "correct folder", SS doesn't deal with saving schematics, worldedit does.
