### ISSUE TITLE
Error when placing schematic

### ISSUE THREAD

**Issue by NotDutchyAnymore** [drtshock/SchematicShop#2]
When trying to place my schematic I am currently getting this error

http://pastebin.com/tCwBcWKq

**Comment by drtshock** [comment]
Which version of towny?

**Comment by NotDutchyAnymore** [comment]
Dev Build: Towny Advanced 0.89.1.0 [1.8]

**Comment by drtshock** [comment]
Looks like the owner returns as null if the land doesn't have an owner. Just pushed a fix.
