### ISSUE TITLE
cant place it down the schematics

### ISSUE THREAD

**Issue by theshadyonehd** [drtshock/SchematicShop#4]
hey have an error which doesn't let me place down the schematic. http://pastebin.com/G9dHbVNr

**Comment by drtshock** [comment]
Did you reload your server or use plugman to load it?

**Comment by theshadyonehd** [comment]
@drtshock  restart the server, always.

**Comment by drtshock** [comment]
Looks like you just have a missing schematic file. Be sure that the ones that your players have are the same ones in the config file and the same ones in your plugin folder. Names are case sensitive.
