### ISSUE TITLE
cant place it down the schematics

### ISSUE THREAD

**Issue by theshadyonehd** [drtshock/SchematicShop#5]
hey have an error which doesn't let me place down the schematic. http://pastebin.com/G9dHbVNr\

still does not work. all names are correct.

**Comment by drtshock** [comment]
Paste removed. Please use https://gist.github.com

**Comment by theshadyonehd** [comment]
https://gist.github.com/theshadyonehd/1181963718902b5432d5

**Comment by drtshock** [comment]
You're trying to place a schematic that doesn't exist. Make sure they are in the SchematicShop schematic's folder. We don't pull them from worldedit.
