### ISSUE TITLE
Not Registering PacketPlayInBlockPlace

### ISSUE THREAD

**Issue by elijahgreen-** [drtshock/SchematicShop#8]
@drtshock 
I am using the absolute latest Spigot 1.8 jar with no protocol hacks or anything. The GUI for the plugin works, and everything else does except when placing the actual schematic. An error comes up in server logs. I've tried using different versions of WG, WE and AWE. 

https://gist.github.com/anonymous/cfea72bf9b047221cbb9

**Comment by drtshock** [comment]
Can you paste me your config.yml and give me a list of the schematics that you have? It looks like it's not reading your schematic file correctly so you likely have something missing somewhere, or something that's case sensitive.

**Comment by elijahgreen-** [comment]
https://gist.github.com/elijahgreen-/98d48a2cef14a2722455
and I only have one schematic with the name of vault.schematic in WorldEdit. 
Would I have to include the .schematic in SchematicShop?

**Comment by drtshock** [comment]
Is it in plugins/SchematicShop/schematics folder?

**Comment by elijahgreen-** [comment]
There is no folder. There's only a config in plugins/SchematicShop
Would I have to create that manually?

**Comment by MineCove** [comment]
Hi elijagreen -

To answer your question - Yes! You need to manually create a schematics folder within your schematicshop folder. Place all of your schematic files there :)

**Comment by drtshock** [comment]
Yes, it says it on the project page :)

"Place schematics in plugins/SchematicShop/schematics folder. Be wary of how you make the schematics as they paste just as if the player were to executive //paste."
