### ISSUE TITLE
Worldedit permission needed

### ISSUE THREAD

**Issue by MineCove** [drtshock/SchematicShop#9]
Players need worldedit.\* in order to place their build. I have attempted worldedit.clipboard.\* and worldedit.schematic.\* 

Since giving players full access to worldedit is foolish indeed, which worldedit node(s) are needed for players to place their builds?

**Comment by drtshock** [comment]
No they don't. They place the block that they take out of the GUI and the server pastes it there.

**Comment by MineCove** [comment]
Since your response, I've painstakingly attempted every work around I could think of with no avail

Here's the process I go through:

Step 1. /schematicshop add Cosmosous example - 

^ Via console, cosmosous is the player's name. Example is the schematic file (example.schematic) that I have placed in plugins/SchematicShop/schematics directory

Step 2. '[BuildShop] Added schematic to account'

Step 3. /ss to open the schematic shop GUI 

Step 4. Recieve the example.schematic block from the schematic shop GUI

Step 5. Place the block on the ground

Step 6. '[BuildShop] Placing your build now!' 

Build does not appear

Execute '/pex user cosmosous add worldedit.*' via console without the quotes

Go through steps 1 - 6 again

Build does appear

At the very least, could you please answer the following so that I may further diagnose the issue:
1. Does schematicshop interact with worldedit at all?
2. Is schematicshop.add the only permission node?
3. Permissions system being used on the example setup ShockNetwork? 

Thank you very much

**Comment by drtshock** [comment]
Shocknetwork uses pex. Users aren't assigned any schematic shop permissions.
1. yes
2. Yes it does. It uses the ClipBoard then executes a paste on behalf of the server, not the player.

**Comment by MineCove** [comment]
Solved:
In the WorldEdit configuration file:

use-inventory:
    enable: true
    allow-override: true

Must be set as

use-inventory:
    enable: false
    allow-override: true

I hope if others have the same issue as I had my findings will help quickly solve their issue. I'll leave you an appropriate review once I've released it on my production server - Thank you for your help

**Comment by drtshock** [comment]
Good to know, I'll be sure to put that on the project page so no one has to suffer through this like you did. Apologies I wasn't aware but thanks a ton for figuring this out!
